language: java
dist: xenial
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

script:
  - mvn cobertura:cobertura

after_success:
  - mvn coveralls:cobertura

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.m2
